language: python

python:
    - 2.7

before_install:
  - git submodule update --init --recursive
  - sudo apt-get install python-dev

install:
  - cd deps/libuv && sh ./autogen.sh && ./configure && make && sudo make install
  - cd ../../
  - sudo python setup.py install

script: python -m unittest discover
